- name: Enable SAP and HA Repositories
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
  - rhel-sap-hana-for-rhel-7-server-rpms
  - rhel-ha-for-rhel-7-server-rpms


- name: Install SAP-HANA tuned profile
  yum: name=tuned-profiles-sap-hana state=latest

- name: Update MOTD
  blockinfile: block="Role SAP-HANA installed"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd

