- name: install Heketi 
  yum: name=heketi state=latest


- name: Update MOTD
  blockinfile: block="Heketi installed"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd

