- name: install Gluster 
  yum: name=redhat-storage-server* state=latest


- name: Update MOTD
  blockinfile: block="Gluster installed"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd


- name: Start gluster deamon
  service: name=glusterd enabled=yes state=started
