- name: Install Ansible
  yum:
    name: https://releases.hashicorp.com/vagrant/1.9.2/vagrant_1.9.2_x86_64.rpm
    state: present
- name: Install Ansible plugins
  shell: "vagrant plugin install {{ item }}"
  with_items:
  - vagrant-libvirt
  - vagrant-hostmanager

- name: Enable NFS
  service: name=nfs enabled=yes state=started

# TODO: May need to add firewall config here.
# See https://42notes.wordpress.com/2015/04/30/notes-on-nfs-firewalld-selinux/

- name: Update MOTD
  blockinfile: block="Vagrant, vagrant-libvirt, vagrant-hostmanager installed"
                insertafter=EOF
                marker="==============================================================="
                dest=/etc/motd
