- name: Print what we are doing
  debug:
    msg: "Setting up volume {{ lv }} for {{ dir }} on {{ sat_dev }}"

- name: Check if the volume doesn't exist already
  stat:
    path: /dev/data/{{ lv }}
    follow: true
  register: volume_status

- block:
  - yum: name=lvm2 state=present
  - lvg: vg=data pvs={{ sat_dev }} state=present
  - lvol: vg=data lv={{ lv }} size={{ size }}
  - filesystem: fstype=xfs dev=/dev/data/{{ lv }}
  - file: name={{ dir }} state=directory
  - mount: name={{ dir }}  src=/dev/data/{{ lv }} fstype=xfs state=mounted
  when: not volume_status.stat.isblk
