- name: enable sat repositories. 
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-6.2-rpms
  
- name: Do LVM if data disk exists
  include: lvm.yml lv={{ item.lv}} size={{ item.size }} dir={{ item.dir }} sat_dev={{ sat_datadev }}
  with_items:
  - { lv: mongodb, size: '25g', dir: "/var/lib/mongodb" }
  - { lv: cache, size: '10g', dir: "/var/cache/pulp" }
  - { lv: pulp, size: '100%FREE', dir: "/var/lib/pulp" }
  when: config_lvm 

- name: Install satellite
  yum: name=satellite state=latest

- name: install Chrony
  yum: name=chrony state=latest

- name: make sure Chrony is running
  service: name=chronyd state=started enabled=yes

- name: Update MOTD
  blockinfile: block="Satellite prepared. You can now run satellite-installer"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd

