- stat: path=/etc/pki/consumer/cert.pem 
  register: registered


- name: Register the box with the Red Hat Portal
  redhat_subscription: state=present 
                       username={{ rh_username }} 
                       password={{ rh_password }} 
                       pool={{ rh_pool }}
  when: registered.stat.exists == false
  

- name: Disable  repositories
  command: "subscription-manager repos --disable=*"
  when: registered.stat.exists == false

- name: Enable Repositories
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-rh-common-rpms
  when: registered.stat.exists == false


- name: upgrade all packages
  yum: name=* state=latest

- name: Update MOTD
  blockinfile: block="Registered with Red Hat CDN"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd
     
