---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libvirt
    - libvirt-devel

- name: enable and start libvirtd
  service: name=libvirtd enabled=yes state=started


- name: Update MOTD
  blockinfile: block="Libvirt Installed"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd
