- name: Enable Repositories
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
  - rhel-7-server-openstack-{{ rhos_release }}-rpms
  - rhel-7-server-openstack-{{ rhos_release }}-director-rpms

- name: upgrade all packages
  yum: name=* state=latest

- name: Update MOTD
  blockinfile: block="Using Red Hat Open Stack Platform release {{ rhos_release }}"
               insertafter=EOF
               marker="==============================================================="
               dest=/etc/motd
     
