- name: Set a MOTD
  template: src=motd.j2
            dest=/etc/motd
            owner=root
            group=root
            mode=0644

- name: Set the timezone
  timezone: name=Europe/Zurich

- name: "Add fqdn to hostfile"
  lineinfile: dest=/etc/hosts regexp='^.*{{ ansible_fqdn }}$' line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}" state=present
  when: ansible_default_ipv4.address is defined

- name: "Add  hostname to hostfile"
  lineinfile: dest=/etc/hosts regexp='^.*{{ ansible_hostname }}$' line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }}" state=present
  when: ansible_default_ipv4.address is defined
